package vista;

public class Sistema extends javax.swing.JFrame {
      private CrearEmpleado registrarEmpleado = new CrearEmpleado();
      private ListarEmpleado listarEmpleado = new ListarEmpleado();
      private CrearPaciente registrarPaciente = new CrearPaciente();
      private ListarPacientes listarPacientes = new ListarPacientes();
      private CrearDepartamento crearDepartamento = new CrearDepartamento();
      private ListarDepartamentos listarDepartamentos = new ListarDepartamentos();
      private CrearPuestoTrabajo crearPuestoTrab = new CrearPuestoTrabajo();
      private ListarPuestoTrabajo listarPuestoTrabajo = new ListarPuestoTrabajo();
    
    private boolean menuEmpleado = false;
    private boolean menuPaciente = false;
    private boolean menuInstalaciones = false;
    
    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        menuEmpleado = true;
        menuPaciente = false;
        menuInstalaciones = false;
        
        jButtonCrearUno.setText("Registrar Nuevo Empleado");
        jButtonListarUno.setText("Listar Empleados");
        jButtonCrearDos.setEnabled(false);
        jButtonListarDos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEmpleado = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jButtonInstalaciones = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonCrearUno = new javax.swing.JButton();
        jButtonListarUno = new javax.swing.JButton();
        jButtonCrearDos = new javax.swing.JButton();
        jButtonListarDos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonEmpleado.setText("Gestionar Empleado");
        jButtonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpleadoActionPerformed(evt);
            }
        });

        jButtonPaciente.setText("Gestionar Paciente");
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });

        jButtonInstalaciones.setText("Gestion Instalaciones");
        jButtonInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstalacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonInstalaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCrearUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUnoActionPerformed(evt);
            }
        });

        jButtonListarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarUnoActionPerformed(evt);
            }
        });

        jButtonCrearDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearDosActionPerformed(evt);
            }
        });

        jButtonListarDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonCrearDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCrearUno, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonListarUno, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jButtonListarDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonListarUno, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jButtonCrearUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCrearDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarDos, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstalacionesActionPerformed
        menuEmpleado = false;
        menuPaciente = false;
        menuInstalaciones = true;
        
        jButtonCrearDos.setEnabled(true);
        jButtonListarDos.setEnabled(true);
        
        jButtonCrearUno.setText("Registrar Departamento");
        jButtonListarUno.setText("Listar Departamento");
        jButtonCrearDos.setText("Registrar Puesto de Trabajo");
        jButtonListarDos.setText("Listar Puesto de Trabajo");
    }//GEN-LAST:event_jButtonInstalacionesActionPerformed

    private void jButtonCrearDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearDosActionPerformed
        this.setVisible(false); 
        crearPuestoTrab.setVisible(true);
    }//GEN-LAST:event_jButtonCrearDosActionPerformed

    private void jButtonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpleadoActionPerformed
        menuEmpleado = true;
        menuPaciente = false;
        menuInstalaciones = false;
        
        jButtonCrearUno.setText("Registrar Nuevo Empleado");
        jButtonListarUno.setText("Listar Empleados");
        jButtonCrearDos.setEnabled(false);
        jButtonListarDos.setEnabled(false);
    }//GEN-LAST:event_jButtonEmpleadoActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        menuEmpleado = false;
        menuPaciente = true;
        menuInstalaciones = false;
        
        jButtonCrearUno.setText("Registrar Nuevo Paciente");
        jButtonListarUno.setText("Listar Paciente");
        jButtonCrearDos.setEnabled(false);
        jButtonListarDos.setEnabled(false);
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonCrearUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUnoActionPerformed
        if(menuEmpleado == true){
            this.setVisible(false);
            registrarEmpleado.setVisible(true);
        }else if(menuPaciente == true){
            this.setVisible(false);
            registrarPaciente.setVisible(true);
        }else if(menuInstalaciones == true){
            this.setVisible(false);
            crearDepartamento.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCrearUnoActionPerformed

    private void jButtonListarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarUnoActionPerformed
        if(menuEmpleado == true){
            this.setVisible(false); //******
            listarEmpleado.setVisible(true);
        }else if(menuPaciente == true){
            this.setVisible(false);
            listarPacientes.setVisible(true);
        }else if(menuInstalaciones == true){
            this.setVisible(false);
            listarDepartamentos.setVisible(true);
        }
    }//GEN-LAST:event_jButtonListarUnoActionPerformed

    private void jButtonListarDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDosActionPerformed
        this.setVisible(false); 
        listarPuestoTrabajo.setVisible(true);
    }//GEN-LAST:event_jButtonListarDosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearDos;
    private javax.swing.JButton jButtonCrearUno;
    private javax.swing.JButton jButtonEmpleado;
    private javax.swing.JButton jButtonInstalaciones;
    private javax.swing.JButton jButtonListarDos;
    private javax.swing.JButton jButtonListarUno;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
