package vista;

import controlador.Empleado;
import controlador.Departamento;
import controlador.PuestoTrabajo;
import controlador.CRUD;
import controlador.Validacion;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CRUEmpleado extends javax.swing.JFrame {

    private Empleado empleado = new Empleado();
    private Departamento departamento = new Departamento();
    private PuestoTrabajo puestoTrabajo = new PuestoTrabajo();
    private Validacion validacion = new Validacion();
    private CRUD crud = new CRUD();
    private Mensaje mensaje = new Mensaje();

    public CRUEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        inicializarComboBox();
    }

    public void mostrarDatosE(Empleado empleado) {
        this.empleado = empleado;
        llenarCampos(empleado);
        desactivarEdicion();
        jButtonRegistar.setEnabled(false);
        jButtonRegistar.setVisible(false);
    }

    public void actualizarDatosE(Empleado empleado) {
        this.empleado = empleado;
        llenarCampos(empleado);
        jButtonRegistar.setText("Actualizar");
    }

    private void desactivarEdicion() {

        jTextFieldApellidos.setEditable(false);
        jTextFieldNombres.setEditable(false);
        jTextFieldCedula.setEditable(false);
        jTextFieldCorreo.setEditable(false);
        jTextFieldTelef.setEditable(false);
        jTextFieldDireccion.setEditable(false);
        jDateChooserCalendario.setEnabled(false);
        jTextFieldUsuario.setEditable(false);
        jTextFieldPassword.setEditable(false);
        jComboBoxDepartamento.setEnabled(false);
        jComboBoxDepartamento.setEditable(false);
        jComboBoxPuestoT.setEditable(false);
        jComboBoxPuestoT.setEnabled(false);
    }

    private void llenarCampos(Empleado empleado) {
        jLabelTitulo.setText("Datos Empleado");
        jTextFieldApellidos.setText(empleado.getApellidos());
        jTextFieldNombres.setText(empleado.getNombres());
        jTextFieldCedula.setText(empleado.getCedula());
        jTextFieldCorreo.setText(empleado.getCorreo());
        jTextFieldTelef.setText(empleado.getTelefono());
        jTextFieldDireccion.setText(empleado.getDireccion());
        try {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = formato.parse(empleado.getFechaNac());
            jDateChooserCalendario.setDate(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(CRUEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextFieldUsuario.setText(empleado.getUsuario());
        jTextFieldPassword.setText(empleado.getPassword());
        jComboBoxDepartamento.setSelectedItem(empleado.getDepartamento().getNombreDep());
        jComboBoxPuestoT.setSelectedItem(empleado.getPuestoTrabajo().getCodigoPuesTra());
    }

    public void inicializarComboBox() {
        String[] departamento = crud.seleccionardatos("departamento", "DEP_NOMBRE");
        String[] puestoT = crud.seleccionardatos("puesto_trabajo", "PDT_NOMBRE");
        for (int i = 0; i < departamento.length; i++) {
            jComboBoxDepartamento.addItem(departamento[i]);
        }
        for (int i = 0; i < puestoT.length; i++) {
            jComboBoxPuestoT.addItem(puestoT[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabelNombres = new javax.swing.JLabel();
        jTextFieldNombres = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelFechaN = new javax.swing.JLabel();
        jDateChooserCalendario = new com.toedter.calendar.JDateChooser();
        jLabelTelef = new javax.swing.JLabel();
        jTextFieldTelef = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabel1PuestoT = new javax.swing.JLabel();
        jComboBoxDepartamento = new javax.swing.JComboBox<>();
        jComboBoxPuestoT = new javax.swing.JComboBox<>();
        jButtonRegistar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("REGISTRAR EMPLEADO");
        jPanel6.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(65, 65, 65));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelApellidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos");
        jPanel1.add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jTextFieldApellidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldApellidos.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldApellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, -1));

        jLabelCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCedula.setText("N. Cedula");
        jPanel1.add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jTextFieldCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldCedula.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 67, 190, -1));

        jLabelNombres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNombres.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombres.setText("Nombres");
        jPanel1.add(jLabelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, 20));

        jTextFieldNombres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNombres.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 210, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 110));

        jPanel2.setBackground(new java.awt.Color(65, 65, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo");

        jTextFieldCorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldCorreo.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });

        jLabelDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion.setText("Dirección");

        jTextFieldDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldDireccion.setForeground(new java.awt.Color(51, 51, 51));

        jLabelFechaN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelFechaN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaN.setText("Fecha de Nacimiento");

        jDateChooserCalendario.setDateFormatString("dd-MM-yyyy");

        jLabelTelef.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTelef.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelef.setText("N. Telef");

        jTextFieldTelef.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTelef.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jTextFieldDireccion))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelFechaN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTelef)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTelef, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelef)
                    .addComponent(jTextFieldTelef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFechaN)
                    .addComponent(jDateChooserCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(22, 22, 22))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 610, 110));

        jPanel3.setBackground(new java.awt.Color(65, 65, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario");

        jLabelPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Contraseña");

        jTextFieldUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(51, 51, 51));

        jTextFieldPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPassword.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPassword)
                    .addComponent(jLabelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jTextFieldPassword))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, 100));

        jPanel4.setBackground(new java.awt.Color(65, 65, 65));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDepartamento.setText("Departamento");
        jPanel4.add(jLabelDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        jLabel1PuestoT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1PuestoT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1PuestoT.setText("Puesto de Trabajo");
        jPanel4.add(jLabel1PuestoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jComboBoxDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxDepartamento.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(jComboBoxDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, -1));

        jComboBoxPuestoT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxPuestoT.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(jComboBoxPuestoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, 24));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 330, 100));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 650, 380));

        jButtonRegistar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegistar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonRegistar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonRegistar.setText("Registrar");
        jButtonRegistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegistarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegistarMouseExited(evt);
            }
        });
        jButtonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 124, 40));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/csrbc.png"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jButtonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarActionPerformed
        //Boton Registrar

        if (!validacion.validarApenNomb(jTextFieldApellidos.getText())) {
            empleado.setApellidos(jTextFieldApellidos.getText());
        } else {
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (!validacion.validarApenNomb(jTextFieldNombres.getText())) {
            empleado.setNombres(jTextFieldNombres.getText());
        } else {
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (!validacion.validarCedula(jTextFieldCedula.getText())) {
            empleado.setCedula(jTextFieldCedula.getText());
        } else {
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (!validacion.validarCorreo(jTextFieldCorreo.getText())) {
            empleado.setCorreo(jTextFieldCorreo.getText());
        } else {
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (!validacion.validarTelf(jTextFieldTelef.getText())) {
            empleado.setTelefono(jTextFieldTelef.getText());
        } else {
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (jDateChooserCalendario.getDate() != null) {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
            String fechaN = formatoFecha.format(jDateChooserCalendario.getDate());
            empleado.setFechaNac(fechaN);
        } else {
            validacion.setMensajeE("ERROR!. El campo Fecha de Nacimiento no se encuentra llenado.");
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (!validacion.camposVacios(jTextFieldDireccion.getText())) {
            empleado.setDireccion(jTextFieldDireccion.getText());
        } else {
            validacion.setMensajeE("ERROR!. El campo Dirección no se encuetra llenado.");
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (!validacion.camposVacios(jTextFieldUsuario.getText())) {
            empleado.setUsuario(jTextFieldUsuario.getText());
        } else {
            validacion.setMensajeE("ERROR!. El campo Usuario no se encuentra llenado.");
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }
        if (!validacion.camposVacios(jTextFieldPassword.getText())) {
            empleado.setPassword(jTextFieldPassword.getText());
        } else {
            validacion.setMensajeE("ERROR!. El campo Password no se encuentra llenado.");
            mensaje.interError();
            mensaje.mostrarM("ERROR EN EL REGISTRO", validacion.getMensajeE());
            return;
        }

        crud.buscarDepartamento(departamento, "DEP_NOMBRE", jComboBoxDepartamento.getSelectedItem().toString());
        empleado.setDepartamento(departamento);
        crud.buscarPuestoT(puestoTrabajo, "PDT_NOMBRE", jComboBoxPuestoT.getSelectedItem().toString());
        empleado.setPuestoTrabajo(puestoTrabajo);

        if (jButtonRegistar.getText().equals("Registrar")) {
            empleado.setCodigoEmpleado("EMP" + crud.obtenerCodigo("empleado"));
            crud.registrarEmpleado(empleado);
            mensaje.setExito(true);
            mensaje.redicListadoEmp();
            mensaje.interExito();
            mensaje.mostrarM("Registro EXITOSO", "El registro se realizó exitosamente");
            this.setVisible(false);
        }else if (jButtonRegistar.getText().equals("Actualizar")){
            crud.actualizarEmpleado(empleado);
            mensaje.setExito(true);
            mensaje.redicListadoEmp();
            mensaje.interExito();
            mensaje.mostrarM("Actualizacion EXITOSO", "La actualizacion se realizó exitosamente");
            this.setVisible(false);
        }
        // Sistema sistema = new Sistema();
        // sistema.setVisible(true);
    }//GEN-LAST:event_jButtonRegistarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
        ListarEmpleado listarEmpleado = new ListarEmpleado();
        listarEmpleado.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRegistarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistarMouseEntered
        jButtonRegistar.setBackground(new Color(168,168,168));
    }//GEN-LAST:event_jButtonRegistarMouseEntered

    private void jButtonRegistarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistarMouseExited
        jButtonRegistar.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_jButtonRegistarMouseExited

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        jButtonSalir.setBackground(new Color(168,168,168));
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        jButtonSalir.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_jButtonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUEmpleado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxDepartamento;
    private javax.swing.JComboBox<String> jComboBoxPuestoT;
    private com.toedter.calendar.JDateChooser jDateChooserCalendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1PuestoT;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFechaN;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelTelef;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldTelef;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
