package vista;

public class Sistema extends javax.swing.JFrame {
    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonPaciente = new javax.swing.JButton();
        jButtonServicios = new javax.swing.JButton();
        jButtonEmpleado = new javax.swing.JButton();
        jButtonPuestoT = new javax.swing.JButton();
        jButtonMedicamento = new javax.swing.JButton();
        jButtonDepartamento = new javax.swing.JButton();
        jButtonFactura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Departamentos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/ImGestPac.png"))); // NOI18N
        jButtonPaciente.setText("Gestionar Paciente");
        jButtonPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 94, 39), new java.awt.Color(255, 95, 39), new java.awt.Color(255, 94, 39), new java.awt.Color(255, 94, 39)));
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 230, 110));

        jButtonServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/ImGestSer.png"))); // NOI18N
        jButtonServicios.setText("Gestion Instalaciones");
        jButtonServicios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 146, 204), new java.awt.Color(0, 146, 204), new java.awt.Color(0, 146, 204), new java.awt.Color(0, 146, 204)));
        jButtonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 230, 120));

        jButtonEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/ImgGestEmp.png"))); // NOI18N
        jButtonEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 170));

        jButtonPuestoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/ImgGestPuestT.png"))); // NOI18N
        jButtonPuestoT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonPuestoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuestoTActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPuestoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 180));

        jButtonMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/ImgGestMed.png"))); // NOI18N
        jButtonMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 180, 170));

        jButtonDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/ImgGestDep.png"))); // NOI18N
        jButtonDepartamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepartamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 180, 180));

        jButtonFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/ImgGenFac.png"))); // NOI18N
        jButtonFactura.setText("Gestionar Empleado");
        jButtonFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 178, 98), new java.awt.Color(0, 178, 98), new java.awt.Color(0, 178, 98), new java.awt.Color(0, 178, 98)));
        jButtonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 230, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosImg/FontoInf.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiciosActionPerformed
        this.setVisible(false);
        ListarServicio listarServicio = new ListarServicio();
        listarServicio.listarSER();
        listarServicio.setVisible(true);
    }//GEN-LAST:event_jButtonServiciosActionPerformed

    private void jButtonMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicamentoActionPerformed
        this.setVisible(false);        
        ListarMedicamento listarMedicamento = new ListarMedicamento();
        listarMedicamento.setVisible(true);
    }//GEN-LAST:event_jButtonMedicamentoActionPerformed

    private void jButtonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturaActionPerformed
        this.setVisible(false);
        ListarServicio listarServicio = new ListarServicio();
        listarServicio.listarSERFAC();
        listarServicio.setVisible(true);
    }//GEN-LAST:event_jButtonFacturaActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        this.setVisible(false);
        ListarPacientes listarPacientes = new ListarPacientes();
        listarPacientes.setVisible(true);
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepartamentoActionPerformed
        
        this.setVisible(false);
        ListarDepartamentos listarDepartamentos = new ListarDepartamentos();
        listarDepartamentos.setVisible(true);
    }//GEN-LAST:event_jButtonDepartamentoActionPerformed

    private void jButtonPuestoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuestoTActionPerformed
        this.setVisible(false);        
        ListarPuestoTrabajo listarPuestoT = new ListarPuestoTrabajo();
        listarPuestoT.setVisible(true);
    }//GEN-LAST:event_jButtonPuestoTActionPerformed

    private void jButtonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpleadoActionPerformed
        this.setVisible(false);
        ListarEmpleado listarEmpleado = new ListarEmpleado();
        listarEmpleado.setVisible(true);
        
    }//GEN-LAST:event_jButtonEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDepartamento;
    private javax.swing.JButton jButtonEmpleado;
    private javax.swing.JButton jButtonFactura;
    private javax.swing.JButton jButtonMedicamento;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonPuestoT;
    private javax.swing.JButton jButtonServicios;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
